
diccionarioArte =[
    {"intro": """


▐▌   ▄    ▐▌   ▗▞▀▚▖ ▄▄▄ █  ▄▄▄  ▄   ▄ ▗▞▀▚▖ ▄▄▄  ▗▞▀▜▌▄▄▄▄  ▗▞▀▚▖
▐▌   ▄    ▐▌   ▐▛▀▀▘█    █ █   █ █ ▄ █ ▐▛▀▀▘█     ▝▚▄▟▌█ █ █ ▐▛▀▀▘
▐▛▀▚▖█    ▐▛▀▚▖▝▚▄▄▖█    █ ▀▄▄▄▀ █▄█▄█ ▝▚▄▄▖█          █   █ ▝▚▄▄▖
▐▌ ▐▌█ ▗▄▖▐▌ ▐▌          █                      ▗▄▖               
      ▐▌ ▐▌                                    ▐▌ ▐▌              
       ▝▀▜▌                                     ▝▀▜▌              
      ▐▙▄▞▘                                    ▐▙▄▞▘              
"""},
    {"vs": """
░▒▓█▓▒░░▒▓█▓▒░░▒▓███████▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░        
 ░▒▓█▓▒▒▓█▓▒░░▒▓█▓▒░        
 ░▒▓█▓▒▒▓█▓▒░ ░▒▓██████▓▒░  
  ░▒▓█▓▓█▓▒░        ░▒▓█▓▒░ 
  ░▒▓█▓▓█▓▒░        ░▒▓█▓▒░ 
   ░▒▓██▓▒░  ░▒▓███████▓▒░ 
    """}
]

personasFamosas = [
    {   "nombre": "Silvestre Stallone",
        "seguidores": 100,
        "descripcion": "Actor conocido por su papel de Rocky Balboa.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Leonardo DiCaprio",
        "seguidores": 229,
        "descripcion": "Actor ganador del Oscar por 'El Renacido'.",
        "pais": "Estados Unidos",
    },
    {       
        "nombre": "Penélope Cruz",
        "seguidores": 150,
        "descripcion": "Actriz ganadora de un Oscar por 'Vicky Cristina Barcelona'.",
        "pais": "España",
    },
    {
        "nombre": "Shakira",
        "seguidores": 300,
        "descripcion": "Cantante y compositora, conocida por su música pop y ritmos latinos.",
        "pais": "Colombia",
    },
    {
        "nombre": "David Beckham",
        "seguidores": 250,
        "descripcion": "Exfutbolista, conocido por su carrera en el Manchester United y la selección inglesa.",
        "pais": "Reino Unido",
    },
    {
        "nombre": "Emma Watson",
        "seguidores": 180,
        "descripcion": "Actriz y activista, famosa por su papel de Hermione Granger en 'Harry Potter'.",
        "pais": "Reino Unido",
    },
    {
        "nombre": "Jackie Chan",
        "seguidores": 220,
        "descripcion": "Actor y artista marcial, conocido por sus películas de acción y comedia.",
        "pais": "China",
    },
    {
        "nombre": "Ariana Grande",
        "seguidores": 350,
        "descripcion": "Cantante y actriz, famosa por su potente voz y éxitos pop.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Cristiano Ronaldo",
        "seguidores": 500,
        "descripcion": "Futbolista, considerado uno de los mejores jugadores de fútbol de todos los tiempos.",
        "pais": "Portugal",
    },
    {
        "nombre": "Emma Stone",
        "seguidores": 170,
        "descripcion": "Actriz ganadora del Oscar por 'La La Land'.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Rihanna",
        "seguidores": 403,
        "descripcion": "Cantante y empresaria, conocida por sus éxitos en la música pop y R&B.",
        "pais": "Barbados",
    },
    {
        "nombre": "Dwayne Johnson",
        "seguidores": 454,
        "descripcion": "Actor y exluchador profesional, conocido como 'The Rock'.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Gal Gadot",
        "seguidores": 308,
        "descripcion": "Actriz y modelo, famosa por su papel de Wonder",
        "pais": "",
    },
    {
        "nombre": "Taylor Swift",
        "seguidores": 689,
        "descripcion": "Cantante y compositora, conocida por sus álbumes de pop y country.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Beyoncé",
        "seguidores": 550,
        "descripcion": "Cantante, actriz y empresaria famosa por su carrera en la música R&B.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Keanu Reeves",
        "seguidores": 401,
        "descripcion": "Actor conocido por sus papeles en 'Matrix' y 'John Wick'.",
        "pais": "Canadá",
    },
    {
        "nombre": "Natalie Portman",
        "seguidores": 312,
        "descripcion": "Actriz y directora, ganadora del Oscar por 'Black Swan'.",
        "pais": "Israel",
    },
    {
        "nombre": "Chris Hemsworth",
        "seguidores": 350,
        "descripcion": "Actor, famoso por su papel de Thor en el Universo Cinematográfico de Marvel.",
        "pais": "Australia",
    },
    {
        "nombre": "Scarlett Johansson",
        "seguidores": 409,
        "descripcion": "Actriz, conocida por sus papeles en 'Lost in Translation' y como Black Widow.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Robert Downey Jr.",
        "seguidores": 500,
        "descripcion": "Actor famoso por su papel de Iron Man en el Universo Cinematográfico de Marvel.",
        "pais": "Estados Unidos",
    },
    {       
        "nombre": "Jennifer Lawrence",
        "seguidores": 350,
        "descripcion": "Actriz ganadora del Oscar por 'Silver Linings Playbook'.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Morgan Freeman",
        "seguidores": 300,
        "descripcion": "Actor y narrador, conocido por su voz distintiva y papeles en películas icónicas.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Emma Roberts",
        "seguidores": 300,
        "descripcion": "Actriz, conocida por sus papeles en 'American Horror Story' y 'Scream Queens'.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Vin Diesel",
        "seguidores": 500,
        "descripcion": "Actor y productor, famoso por su papel de Dominic Toretto en 'Fast & Furious'.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Miley Cyrus",
        "seguidores": 500,
        "descripcion": "Cantante y actriz, conocida por su carrera musical y su papel en 'Hannah Montana'.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Justin Bieber",
        "seguidores": 500,
        "descripcion": "Cantante, famoso por sus éxitos pop y su influencia en las redes sociales.",
        "pais": "Canadá",
    },
    {
        "nombre": "Selena Gomez",
        "seguidores": 500,
        "descripcion": "Cantante y actriz, conocida por su música y su papel en 'Wizards of Waverly Place'.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Katy Perry",
        "seguidores": 450,
        "descripcion": "Cantante, famosa por sus éxitos pop y su estilo colorido.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Adele",
        "seguidores": 400,
        "descripcion": "Cantante, conocida por su poderosa voz y baladas emotivas.",
        "pais": "Reino Unido",
    },
    {
        "nombre": "Eminem",
        "seguidores": 500,
        "descripcion": "Rapper, considerado uno de los mejores MCs de todos los tiempos.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Billie Eilish",
        "seguidores": 700,
        "descripcion": "Cantante y compositora, famosa por su estilo único y música innovadora.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Drake",
        "seguidores": 800,
        "descripcion": "Rapper y cantante, conocido por sus éxitos en el hip-hop y R&B.",
        "pais": "Canadá",
    },
    {
        "nombre": "Kendrick Lamar",
        "seguidores": 619,
        "descripcion": "Rapper, ganador de múltiples premios Grammy y aclamado por su lírica.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Lady Gaga",
        "seguidores": 700,
        "descripcion": "Cantante, actriz y activista, conocida por su música pop y estilo extravagante.",
        "pais": "Estados Unidos",
    },
    {
        "nombre": "Post Malone",
        "seguidores": 500,
        "descripcion": "Rapper y cantante, famoso por su mezcla de géneros musicales.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Travis Scott",
        "seguidores": 600,
        "descripcion": "Rapper y productor, conocido por su estilo innovador y colaboraciones.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Cardi B",
        "seguidores": 550,
        "descripcion": "Rapper y personalidad de televisión, famosa por su estilo audaz y éxitos en el hip-hop.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Bad Bunny",
        "seguidores": 900,
        "descripcion": "Cantante y rapero, conocido por su música urbana y reguetón.",
        "pais": "Puerto Rico",
    },
    {    "nombre": "J Balvin",
        "seguidores": 820,
        "descripcion": "Cantante de reguetón, conocido por sus éxitos en la música latina.",
        "pais": "Colombia",
    },
    {   "nombre": "Maluma",
        "seguidores": 700,
        "descripcion": "Cantante de reguetón y pop latino, famoso por sus colaboraciones internacionales.",
        "pais": "Colombia",
    },
    {   "nombre": "Ozuna",
        "seguidores": 750,
        "descripcion": "Cantante de reguetón y música urbana, conocido por su estilo melódico.",
        "pais": "Puerto Rico",
    },
    {   "nombre": "Karol G",
        "seguidores": 610,
        "descripcion": "Cantante de reguetón y música urbana, famosa por sus éxitos en la música latina.",
        "pais": "Colombia",
    },
    {   "nombre": "Anuel AA",
        "seguidores": 650,
        "descripcion": "Rapper y cantante, conocido por su estilo urbano y colaboraciones en el reguetón.",
        "pais": "Puerto Rico",
    },
    {   "nombre": "Nicky Jam",
        "seguidores": 700,
        "descripcion": "Cantante y compositor, famoso por su música urbana y reguetón.",
        "pais": "Puerto Rico",
    },
    {   "nombre": "Becky G",
        "seguidores": 534,
        "descripcion": "Cantante y actriz de ascendencia mexicana, conocida por su música pop y reguetón.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Danna Paola",
        "seguidores": 550,
        "descripcion": "Actriz y cantante, famosa por su música pop y papeles en telenovelas.",
        "pais": "México",
    },
    {   "nombre": "Thalía",
        "seguidores": 600,
        "descripcion": "Cantante y actriz, conocida por su carrera en la música pop y telenovelas.",
        "pais": "México",
    },
    {   "nombre": "Luis Fonsi",
        "seguidores": 700,
        "descripcion": "Cantante, famoso por su éxito mundial 'Despacito'.",
        "pais": "Puerto Rico",
    },
    {   "nombre": "Juanes",
        "seguidores": 650,
        "descripcion": "Cantante, conocido por su música pop y rock en español.",
        "pais": "Colombia", 
    },
    {   "nombre": "Alejandro Sanz",
        "seguidores": 609,
        "descripcion": "Cantante y compositor, famoso por su música pop y baladas románticas.",
        "pais": "España",
    },
    {   "nombre": "Pablo Alborán",
        "seguidores": 393,
        "descripcion": "Cantante y compositor, conocido por su música pop y baladas emotivas.",
        "pais": "España",
    },
    {   "nombre": "Rosalía",
        "seguidores": 809,
        "descripcion": "Cantante, famosa por su fusión de flamenco y música urbana.",
        "pais": "España",
    },
    {   "nombre": "Vetusta Morla",
        "seguidores": 901,
        "descripcion": "Banda de rock alternativo, conocida por su estilo único y letras poéticas.",
        "pais": "España",
    },
    {   "nombre": "Carl Sagan",
        "seguidores": 1000,
        "descripcion": "Astrónomo, astrofísico y divulgador científico, conocido por su trabajo en la popularización de la ciencia.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Albert Einstein",
        "seguidores": 1200,
        "descripcion": "Físico teórico, famoso por desarrollar la teoría de la relatividad.",
        "pais": "Alemania",
    },
    {   "nombre": "Marie Curie",
        "seguidores": 800,
        "descripcion": "Científica pionera en el estudio de la radiactividad, primera mujer en ganar un Premio Nobel.",
        "pais": "Polonia",
    },
    {   "nombre": "Isaac Newton",
        "seguidores": 1500,
        "descripcion": "Matemático y físico, conocido por sus leyes del movimiento y la gravitación universal.",
        "pais": "Reino Unido",
    },
    {   "nombre": "Angel Merkel",
         "seguidores": 900,
        "descripcion": "Política alemana, primera mujer en ocupar el cargo de Canciller de Alemania.",
        "pais": "Alemania",
    },
    {   "nombre": "Tommy Shelby",
        "seguidores": 1100,
        "descripcion": "Personaje ficticio de la serie 'Peaky Blinders', conocido por su astucia y liderazgo.",
        "pais": "Reino Unido",
    },
    {   "nombre": "Elon Musk",
        "seguidores": 2000,
        "descripcion": "Empresario y magnate tecnológico, CEO de Tesla y SpaceX.",
        "pais": "Sudáfrica",
    },
    {   "nombre": "Steve Jobs",
        "seguidores": 1800,
        "descripcion": "Co-fundador de Apple Inc., conocido por su innovación en tecnología.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Bill Gates",
        "seguidores": 1700,
        "descripcion": "Co-fundador de Microsoft, filántropo y empresario.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Mark Zuckerberg",
        "seguidores": 1900,
        "descripcion": "Co-fundador de Facebook, conocido por su impacto en las redes sociales.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Jeff Bezos",
        "seguidores": 1900,
        "descripcion": "Fundador de Amazon, empresario y magnate tecnológico.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Walt Disney",
        "seguidores": 1400,
        "descripcion": "Empresario y productor de cine, fundador de The Walt Disney Company.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Oprah Winfrey",
        "seguidores": 1300,
        "descripcion": "Presentadora de televisión, productora y filántropa.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Tonny Robbins",
        "seguidores": 1300,
        "descripcion": "Autor y orador motivacional, conocido por sus seminarios de desarrollo personal.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Malala Yousafzai",
        "seguidores": 1100,
        "descripcion": "Activista por la educación de las niñas y ganadora del Premio Nobel de la Paz.",
        "pais": "Pakistán",
    },
    {   "nombre": "Carlos Slim",
        "seguidores": 1050,
        "descripcion": "Empresario mexicano, uno de los hombres más ricos del mundo.",
        "pais": "México",
    },
    {   "nombre": "Richard Branson",
        "seguidores": 950,
        "descripcion": "Empresario británico, fundador del Grupo Virgin.",
        "pais": "Reino Unido",
    },
    {   "nombre": "Angela Davis",
        "seguidores": 900,
        "descripcion": "Activista y académica estadounidense, conocida por su trabajo en derechos civiles.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Barack Obama",
        "seguidores": 2000,
        "descripcion": "44º presidente de los Estados Unidos, conocido por su enfoque en la reforma sanitaria y los derechos civiles.",
        "pais": "Estados Unidos",
    },
    {   "nombre": "Nelson Mandela",
        "seguidores": 1800,
        "descripcion": "Activista sudafricano, líder en la lucha contra el apartheid y primer presidente negro de Sudáfrica.",
        "pais": "Sudáfrica",
    },
    {   "nombre": "Martin Luther King Jr.",
        "seguidores": 1600,
        "descripcion": "Activista estadounidense, líder del movimiento por los derechos civiles.",
        "pais": "Estados Unidos",
        "pais": "Sudáfrica",
    }         
]